name: Build ffmuc firmware

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_firmware_on_arm64:
    strategy:
      fail-fast: false
      matrix:
        target: ["x86-64"]
    runs-on: "ARM64"
    container:
      image: ubuntu:20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build dependencies
        run: |
          ./scripts/install_build_dependencies.sh
      - name: build target ${{ matrix.target }}
        id: compile
        run: |
          make BROKEN=1 GLUON_TARGETS=${{ matrix.target }} V=s
          echo "::set-output name=status::success"
      - name: Upload firmware ${{ matrix.target }}
        uses: actions/upload-artifact@master
        if: steps.compile.outputs.status == 'success'
        with:
          name: ${{ matrix.target }}_output
          path: ./output
