name: Test github-runner

on:
  workflow_dispatch:
  push:

jobs:
  test_arm64_runner:
    runs-on: "ARM64"
    container:
      image: ubuntu:20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
